EXACT: dict[str, dict] = {
    "French_Paris": {"iso3": "FRA", "role": "regional"},
    "French_Nord": {"iso3": "FRA", "role": "regional"},
    "French_Pas-de-Calais": {"iso3": "FRA", "role": "regional"},
    "French_Seine-Maritime": {"iso3": "FRA", "role": "regional"},
    "French_Brittany": {"iso3": "FRA", "role": "regional"},
    "French_Alsace": {"iso3": "FRA", "role": "regional"},
    "French_Auvergne": {"iso3": "FRA", "role": "regional"},
    "French_Occitanie": {"iso3": "FRA", "role": "regional"},
    "French_Provence": {"iso3": "FRA", "role": "regional"},
    "French_Corsica": {"iso3": "FRA", "role": "regional"},
    "French_Bearn": {"iso3": "FRA", "role": "regional"},
    "French_Bigorre": {"iso3": "FRA", "role": "regional"},
    "French_Chalosse": {"iso3": "FRA", "role": "regional"},
    "French_South": {"iso3": "FRA", "role": "regional"},
    "Basque_French": {"iso3": "FRA", "role": "regional"},
    "Basque_Lower_Navarre": {"iso3": "FRA", "role": "regional"},
    "Basque_Soule": {"iso3": "FRA", "role": "regional"},
    "BelgianA": {"iso3": "BEL", "role": "regional", "nuts": ["BE2"]},
    "BelgianB": {"iso3": "BEL", "role": "regional", "nuts": ["BE1"]},
    "BelgianC": {"iso3": "BEL", "role": "regional", "nuts": ["BE3"]},
    "Dutch": {"iso3": "NLD", "role": "national"},
    "English": {"iso3": "GBR", "role": "national", "nuts": ["UKC", "UKD", "UKE", "UKF", "UKG", "UKH", "UKI", "UKJ", "UKK"]},
    "English_Cornwall": {"iso3": "GBR", "role": "regional", "nuts": ["UKK"]},
    "Scottish": {"iso3": "GBR", "role": "regional", "nuts": ["UKM"]},
    "Welsh": {"iso3": "GBR", "role": "regional", "nuts": ["UKL"]},
    "Irish": {"iso3": "IRL", "role": "national"},
    "Orcadian": {"iso3": "GBR", "role": "regional", "nuts": ["UKM"]},
    "Shetlandic": {"iso3": "GBR", "role": "regional", "nuts": ["UKM"]},
    "Icelandic": {"iso3": "ISL", "role": "national"},
    "Portuguese": {"iso3": "PRT", "role": "national"},
    "Spanish_Galicia": {"iso3": "ESP", "role": "regional", "nuts": ["ES11"]},
    "Spanish_Asturias": {"iso3": "ESP", "role": "regional", "nuts": ["ES12"]},
    "Spanish_Cantabria": {"iso3": "ESP", "role": "regional", "nuts": ["ES13"]},
    "Spanish_Pais_Vasco": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Spanish_Biscay": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Spanish_Navarra": {"iso3": "ESP", "role": "regional", "nuts": ["ES22"]},
    "Spanish_La_Rioja": {"iso3": "ESP", "role": "regional", "nuts": ["ES23"]},
    "Spanish_Aragon": {"iso3": "ESP", "role": "regional", "nuts": ["ES24"]},
    "Spanish_Aragon_North": {"iso3": "ESP", "role": "regional", "nuts": ["ES24"]},
    "Spanish_Cataluna": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Barcelones": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Catalunya_Central": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Girona": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Lleida": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Penedes": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Peri-Barcelona": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Pirineu": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Camp_de_Tarragona": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Terres_de_l'Ebre": {"iso3": "ESP", "role": "regional", "nuts": ["ES51"]},
    "Spanish_Valencia": {"iso3": "ESP", "role": "regional", "nuts": ["ES52"]},
    "Spanish_Alacant": {"iso3": "ESP", "role": "regional", "nuts": ["ES52"]},
    "Spanish_Castello": {"iso3": "ESP", "role": "regional", "nuts": ["ES52"]},
    "Spanish_Baleares": {"iso3": "ESP", "role": "regional", "nuts": ["ES53"]},
    "Spanish_Mallorca": {"iso3": "ESP", "role": "regional", "nuts": ["ES53"]},
    "Spanish_Menorca": {"iso3": "ESP", "role": "regional", "nuts": ["ES53"]},
    "Spanish_Eivissa": {"iso3": "ESP", "role": "regional", "nuts": ["ES53"]},
    "Spanish_Castilla_Y_Leon": {"iso3": "ESP", "role": "regional", "nuts": ["ES41"]},
    "Spanish_Burgos": {"iso3": "ESP", "role": "regional", "nuts": ["ES41"]},
    "Spanish_Soria": {"iso3": "ESP", "role": "regional", "nuts": ["ES41"]},
    "Spanish_Castilla_La_Mancha": {"iso3": "ESP", "role": "regional", "nuts": ["ES42"]},
    "Spanish_Extremadura": {"iso3": "ESP", "role": "regional", "nuts": ["ES43"]},
    "Spanish_Andalucia": {"iso3": "ESP", "role": "regional", "nuts": ["ES61"]},
    "Spanish_Murcia": {"iso3": "ESP", "role": "regional", "nuts": ["ES62"]},
    "Spanish_Canarias": {"iso3": "ESP", "role": "regional", "nuts": ["ES70"]},
    "Basque_Spanish": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Basque_Araba": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Basque_Baztan": {"iso3": "ESP", "role": "regional", "nuts": ["ES22"]},
    "Basque_Biscay": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Basque_Gipuzkoa": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Basque_Gipuzkoa_Southwest": {"iso3": "ESP", "role": "regional", "nuts": ["ES21"]},
    "Basque_Navarre_Center": {"iso3": "ESP", "role": "regional", "nuts": ["ES22"]},
    "Basque_Navarre_North": {"iso3": "ESP", "role": "regional", "nuts": ["ES22"]},
    "Basque_Roncal": {"iso3": "ESP", "role": "regional", "nuts": ["ES22"]},
}
