EXACT.update({
    "Italian_Piedmont": {"iso3": "ITA", "role": "regional", "nuts": ["ITC1"]},
    "Italian_Aosta_Valley": {"iso3": "ITA", "role": "regional", "nuts": ["ITC2"]},
    "Italian_Liguria": {"iso3": "ITA", "role": "regional", "nuts": ["ITC3"]},
    "Italian_Lombardy": {"iso3": "ITA", "role": "regional", "nuts": ["ITC4"]},
    "Italian_Bergamo": {"iso3": "ITA", "role": "regional", "nuts": ["ITC4"]},
    "Italian_Veneto": {"iso3": "ITA", "role": "regional", "nuts": ["ITH3"]},
    "Italian_Trentino_Alto_Adige": {"iso3": "ITA", "role": "regional", "nuts": ["ITH1", "ITH2"]},
    "Italian_Friuli_Venezia_Giulia_Sappada": {"iso3": "ITA", "role": "regional", "nuts": ["ITH4"]},
    "Italian_Emilia": {"iso3": "ITA", "role": "regional", "nuts": ["ITH5"]},
    "Italian_Northeast": {"iso3": "ITA", "role": "regional", "nuts": ["ITH3", "ITH4", "ITH5"]},
    "Italian_Tuscany": {"iso3": "ITA", "role": "regional", "nuts": ["ITI1"]},
    "Italian_Umbria": {"iso3": "ITA", "role": "regional", "nuts": ["ITI2"]},
    "Italian_Marche": {"iso3": "ITA", "role": "regional", "nuts": ["ITI3"]},
    "Italian_Lazio": {"iso3": "ITA", "role": "regional", "nuts": ["ITI4"]},
    "Italian_Abruzzo": {"iso3": "ITA", "role": "regional", "nuts": ["ITF1"]},
    "Italian_Molise": {"iso3": "ITA", "role": "regional", "nuts": ["ITF2"]},
    "Italian_Campania": {"iso3": "ITA", "role": "regional", "nuts": ["ITF3"]},
    "Italian_Apulia": {"iso3": "ITA", "role": "regional", "nuts": ["ITF4"]},
    "Italian_Basilicata": {"iso3": "ITA", "role": "regional", "nuts": ["ITF5"]},
    "Italian_Calabria": {"iso3": "ITA", "role": "regional", "nuts": ["ITF6"]},
    "Sicilian_East": {"iso3": "ITA", "role": "regional", "nuts": ["ITG1"]},
    "Sicilian_West": {"iso3": "ITA", "role": "regional", "nuts": ["ITG1"]},
    "Sardinian": {"iso3": "ITA", "role": "regional", "nuts": ["ITG2"]},
    "Swiss_French": {"iso3": "CHE", "role": "regional", "nuts": ["CH01"]},
    "Swiss_German": {"iso3": "CHE", "role": "regional", "nuts": ["CH02", "CH03", "CH04", "CH05", "CH06"]},
    "Swiss_Italian": {"iso3": "CHE", "role": "regional", "nuts": ["CH07"]},
    "Austrian": {"iso3": "AUT", "role": "national"},
    "German": {"iso3": "DEU", "role": "national"},
    "German_East": {"iso3": "DEU", "role": "regional", "nuts": ["DE4", "DE8", "DED", "DEE", "DEG"]},
    "German_Hamburg": {"iso3": "DEU", "role": "regional", "nuts": ["DE6"]},
    "German_Erlangen": {"iso3": "DEU", "role": "regional", "nuts": ["DE2"]},
    "Danish": {"iso3": "DNK", "role": "national"},
    "Swedish": {"iso3": "SWE", "role": "national"},
    "Norwegian": {"iso3": "NOR", "role": "national"},
    "Polish": {"iso3": "POL", "role": "national"},
    "Czech": {"iso3": "CZE", "role": "national"},
    "Slovakian": {"iso3": "SVK", "role": "national"},
    "Hungarian": {"iso3": "HUN", "role": "national"},
    "Slovenian": {"iso3": "SVN", "role": "national"},
    "Croatian": {"iso3": "HRV", "role": "national"},
    "Bosnian": {"iso3": "BIH", "role": "national"},
    "Serbian": {"iso3": "SRB", "role": "national"},
    "Montenegrin": {"iso3": "MNE", "role": "national"},
    "Macedonian": {"iso3": "MKD", "role": "national"},
    "Albanian": {"iso3": "ALB", "role": "national"},
    "Bulgarian": {"iso3": "BGR", "role": "national"},
    "Romanian": {"iso3": "ROU", "role": "national"},
    "Moldovan": {"iso3": "MDA", "role": "national"},
    "Belarusian": {"iso3": "BLR", "role": "national"},
    "Latvian": {"iso3": "LVA", "role": "national"},
    "Estonian": {"iso3": "EST", "role": "national"},
    "Maltese": {"iso3": "MLT", "role": "national"},
    "Cypriot": {"iso3": "CYP", "role": "national"},
    "Japanese": {"iso3": "JPN", "role": "national"},
})

TOKEN_ISO = {
    "French": "FRA", "Spanish": "ESP", "Italian": "ITA", "German": "DEU",
    "English": "GBR", "Greek": "GRC", "Russian": "RUS", "Ukrainian": "UKR",
    "Turkish": "TUR", "Han": "CHN", "Japanese": "JPN", "Korean": "KOR",
    "Polish": "POL", "Finnish": "FIN", "Swedish": "SWE", "Norwegian": "NOR",
    "Danish": "DNK", "Dutch": "NLD", "Belgian": "BEL", "Swiss": "CHE",
    "Portuguese": "PRT", "Irish": "IRL", "Albanian": "ALB", "Bulgarian": "BGR",
    "Romanian": "ROU", "Hungarian": "HUN", "Czech": "CZE", "Croatian": "HRV",
    "Serbian": "SRB", "Lithuanian": "LTU", "Latvian": "LVA", "Estonian": "EST",
    "Moroccan": "MAR", "Algerian": "DZA", "Tunisian": "TUN", "Egyptian": "EGY",
    "Lebanese": "LBN", "Syrian": "SYR", "Iranian": "IRN", "Iraqi": "IRQ",
    "Georgian": "GEO", "Armenian": "ARM", "Azerbaijani": "AZE", "Israeli": "ISR",
    "Chinese": "CHN", "Thai": "THA", "Vietnamese": None, "Indian": "IND",
    "Bengali": "BGD", "Pakistani": "PAK", "Afghan": "AFG", "Kazakh": "KAZ",
    "Brazilian": "BRA", "Mexican": "MEX", "Canadian": "CAN", "American": "USA",
    "Australian": "AUS", "Ethiopian": "ETH", "Nigerian": "NGA", "Kinh": "VNM",
    "Sardinian": "ITA", "Sicilian": "ITA", "Basque": "ESP", "Ashkenazi": None,
}

DIASPORA_TOKENS = {
    "Ashkenazi", "Jew", "_Jew", "Roma_", "Romaniote", "Karaite",
}
WEST_ISO = {"FRA", "BEL", "NLD", "LUX", "DEU", "CHE", "AUT", "GBR", "IRL", "ESP", "PRT", "ITA", "DNK"}
EUROPE_ISO_EXTRA = {"TUR", "CYP", "GEO", "ARM", "AZE", "ISR"}
